using System;
using System.Collections.Generic;
using UnityEngine.EventSystems;

namespace UnityEngine.XR.iOS
{
	public class UnityARHitTestExample : MonoBehaviour
	{
		public Transform m_HitTransform;
		public float maxRayDistance = 30.0f;
		public LayerMask collisionLayer = 1 << 10;  //ARKitPlane layer

		public GameObject bedPrefab;
		public GameObject sofaPrefab;
		public GameObject chairPrefab;
		public GameObject coffeeTablePrefab;
		public GameObject shelfPrefab;
		public GameObject lampPrefab;

		private GameObject selectedGameObject;
		private List<GameObject> spawnedObjects = new List<GameObject>(); // keep track of spawned objects
		private GameObject objectToMove;

		void Start()
		{
			objectToMove = null;
		}

        bool HitTestWithResultType (ARPoint point, ARHitTestResultType resultTypes)
        {
            List<ARHitTestResult> hitResults = UnityARSessionNativeInterface.GetARSessionNativeInterface ().HitTest (point, resultTypes);
            if (hitResults.Count > 0) {
                foreach (var hitResult in hitResults) {
                    Debug.Log ("Got hit!");
                    m_HitTransform.position = UnityARMatrixOps.GetPosition (hitResult.worldTransform);
                    m_HitTransform.rotation = UnityARMatrixOps.GetRotation (hitResult.worldTransform);
                    Debug.Log (string.Format ("x:{0:0.######} y:{1:0.######} z:{2:0.######}", m_HitTransform.position.x, m_HitTransform.position.y, m_HitTransform.position.z));

                    	if (ButtonClick.chosenButton == "BedButton") {
	                    	selectedGameObject = Instantiate(bedPrefab, m_HitTransform.position, m_HitTransform.rotation);
	                    } else if (ButtonClick.chosenButton == "SofaButton") {
	                    	selectedGameObject = Instantiate(sofaPrefab, m_HitTransform.position, m_HitTransform.rotation);
	                    } else if (ButtonClick.chosenButton == "ChairButton") {
	                    	selectedGameObject = Instantiate(chairPrefab, m_HitTransform.position, m_HitTransform.rotation);
	                    } else if (ButtonClick.chosenButton == "CoffeeTableButton") {
	                    	selectedGameObject = Instantiate(coffeeTablePrefab, m_HitTransform.position, m_HitTransform.rotation);
	                    } else if (ButtonClick.chosenButton == "ShelfButton") {
	                    	selectedGameObject = Instantiate(shelfPrefab, m_HitTransform.position, m_HitTransform.rotation);
	                    } else if (ButtonClick.chosenButton == "LampButton") {
	                    	selectedGameObject = Instantiate(lampPrefab, m_HitTransform.position, m_HitTransform.rotation);
	                    } else {
	                    	selectedGameObject = null;
	                    }

                    	selectedGameObject = null;
                    return true;
                }
            }
            return false;
        }
		
		// Update is called once per frame
		void Update () {
			#if UNITY_EDITOR   //we will only use this script on the editor side, though there is nothing that would prevent it from working on device
			if (Input.GetMouseButtonDown (0)) {
				Ray ray = Camera.main.ScreenPointToRay (Input.mousePosition);
				RaycastHit hit;
				
				//we'll try to hit one of the plane collider gameobjects that were generated by the plugin
				//effectively similar to calling HitTest with ARHitTestResultType.ARHitTestResultTypeExistingPlaneUsingExtent
				if (Physics.Raycast (ray, out hit, maxRayDistance, collisionLayer)) {
					//we're going to get the position from the contact point
					m_HitTransform.position = hit.point;
					Debug.Log (string.Format ("x:{0:0.######} y:{1:0.######} z:{2:0.######}", m_HitTransform.position.x, m_HitTransform.position.y, m_HitTransform.position.z));

					//and the rotation from the transform of the plane collider
					m_HitTransform.rotation = hit.transform.rotation;
				}
			}
			#else
			if (Input.touchCount > 0 && m_HitTransform != null)
			{
				var touch = Input.GetTouch(0);
				if (touch.phase == TouchPhase.Began && !EventSystem.current.IsPointerOverGameObject())
				{
					var screenPosition = Camera.main.ScreenToViewportPoint(touch.position);
					ARPoint point = new ARPoint {
						x = screenPosition.x,
						y = screenPosition.y
					};

					Ray raycast = Camera.main.ScreenPointToRay(touch.position);
					RaycastHit hitObject;
					if (Physics.Raycast(raycast, out hitObject)) {
						if (hitObject.collider.CompareTag("Furniture")) {
							if(ButtonClick.chosenButton == "DeleteButton") {
								Destroy(hitObject.collider.gameObject);
								ButtonClick.chosenButton = "";
							}
						}
					}

                    // prioritize reults types
                    ARHitTestResultType[] resultTypes = {
						//ARHitTestResultType.ARHitTestResultTypeExistingPlaneUsingGeometry,
                        ARHitTestResultType.ARHitTestResultTypeExistingPlaneUsingExtent, 
                        // if you want to use infinite planes use this:
                        //ARHitTestResultType.ARHitTestResultTypeExistingPlane,
                        //ARHitTestResultType.ARHitTestResultTypeEstimatedHorizontalPlane, 
						//ARHitTestResultType.ARHitTestResultTypeEstimatedVerticalPlane, 
						//ARHitTestResultType.ARHitTestResultTypeFeaturePoint
                    }; 
					
                    foreach (ARHitTestResultType resultType in resultTypes)
                    {
                        if (HitTestWithResultType (point, resultType))
                        {
                            return;
                        }
                    }
				}

				if (touch.phase == TouchPhase.Moved && !EventSystem.current.IsPointerOverGameObject())
				{
					Ray raycast = Camera.main.ScreenPointToRay(touch.position);
					RaycastHit hitObject;
					if (Physics.Raycast(raycast, out hitObject)) {
						if (hitObject.collider.CompareTag("Furniture")) {
							if (ButtonClick.chosenButton == "MoveButton") {
								objectToMove = hitObject.collider.gameObject;
							} else {
								objectToMove = null;
							}
						}
					}
				}

				if (objectToMove != null) {
					Vector3 touchPosition = Camera.main.ScreenToWorldPoint(new Vector3(touch.position.x, touch.position.y, Camera.main.nearClipPlane));
                	objectToMove.transform.position = Vector3.Lerp(transform.position, new Vector3(touchPosition.x, objectToMove.transform.position.y, objectToMove.transform.position.y), Time.deltaTime * 1.0f);
				}
			}
			#endif

		}
	}
}

